// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EntityMessages.proto

#ifndef PROTOBUF_EntityMessages_2eproto__INCLUDED
#define PROTOBUF_EntityMessages_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_EntityMessages_2eproto();
void protobuf_AssignDesc_EntityMessages_2eproto();
void protobuf_ShutdownFile_EntityMessages_2eproto();

class ProtoMessageVector;
class ProtoMessageRPC;

// ===================================================================

class ProtoMessageVector : public ::google::protobuf::Message {
 public:
  ProtoMessageVector();
  virtual ~ProtoMessageVector();

  ProtoMessageVector(const ProtoMessageVector& from);

  inline ProtoMessageVector& operator=(const ProtoMessageVector& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoMessageVector& default_instance();

  void Swap(ProtoMessageVector* other);

  // implements Message ----------------------------------------------

  inline ProtoMessageVector* New() const { return New(NULL); }

  ProtoMessageVector* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoMessageVector& from);
  void MergeFrom(const ProtoMessageVector& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ProtoMessageVector* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // optional float y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // @@protoc_insertion_point(class_scope:ProtoMessageVector)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  float x_;
  float y_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_EntityMessages_2eproto();
  friend void protobuf_AssignDesc_EntityMessages_2eproto();
  friend void protobuf_ShutdownFile_EntityMessages_2eproto();

  void InitAsDefaultInstance();
  static ProtoMessageVector* default_instance_;
};
// -------------------------------------------------------------------

class ProtoMessageRPC : public ::google::protobuf::Message {
 public:
  ProtoMessageRPC();
  virtual ~ProtoMessageRPC();

  ProtoMessageRPC(const ProtoMessageRPC& from);

  inline ProtoMessageRPC& operator=(const ProtoMessageRPC& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoMessageRPC& default_instance();

  void Swap(ProtoMessageRPC* other);

  // implements Message ----------------------------------------------

  inline ProtoMessageRPC* New() const { return New(NULL); }

  ProtoMessageRPC* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoMessageRPC& from);
  void MergeFrom(const ProtoMessageRPC& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ProtoMessageRPC* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool val = 1;
  void clear_val();
  static const int kValFieldNumber = 1;
  bool val() const;
  void set_val(bool value);

  // @@protoc_insertion_point(class_scope:ProtoMessageRPC)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  bool val_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_EntityMessages_2eproto();
  friend void protobuf_AssignDesc_EntityMessages_2eproto();
  friend void protobuf_ShutdownFile_EntityMessages_2eproto();

  void InitAsDefaultInstance();
  static ProtoMessageRPC* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ProtoMessageVector

// optional float x = 1;
inline void ProtoMessageVector::clear_x() {
  x_ = 0;
}
inline float ProtoMessageVector::x() const {
  // @@protoc_insertion_point(field_get:ProtoMessageVector.x)
  return x_;
}
inline void ProtoMessageVector::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:ProtoMessageVector.x)
}

// optional float y = 2;
inline void ProtoMessageVector::clear_y() {
  y_ = 0;
}
inline float ProtoMessageVector::y() const {
  // @@protoc_insertion_point(field_get:ProtoMessageVector.y)
  return y_;
}
inline void ProtoMessageVector::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:ProtoMessageVector.y)
}

// -------------------------------------------------------------------

// ProtoMessageRPC

// optional bool val = 1;
inline void ProtoMessageRPC::clear_val() {
  val_ = false;
}
inline bool ProtoMessageRPC::val() const {
  // @@protoc_insertion_point(field_get:ProtoMessageRPC.val)
  return val_;
}
inline void ProtoMessageRPC::set_val(bool value) {
  
  val_ = value;
  // @@protoc_insertion_point(field_set:ProtoMessageRPC.val)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_EntityMessages_2eproto__INCLUDED
