// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NetworkStructures.proto

#ifndef PROTOBUF_NetworkStructures_2eproto__INCLUDED
#define PROTOBUF_NetworkStructures_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_NetworkStructures_2eproto();
void protobuf_AssignDesc_NetworkStructures_2eproto();
void protobuf_ShutdownFile_NetworkStructures_2eproto();

class IPacketTest;

// ===================================================================

class IPacketTest : public ::google::protobuf::Message {
 public:
  IPacketTest();
  virtual ~IPacketTest();

  IPacketTest(const IPacketTest& from);

  inline IPacketTest& operator=(const IPacketTest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const IPacketTest& default_instance();

  void Swap(IPacketTest* other);

  // implements Message ----------------------------------------------

  inline IPacketTest* New() const { return New(NULL); }

  IPacketTest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const IPacketTest& from);
  void MergeFrom(const IPacketTest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(IPacketTest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 test_uint = 1;
  bool has_test_uint() const;
  void clear_test_uint();
  static const int kTestUintFieldNumber = 1;
  ::google::protobuf::uint32 test_uint() const;
  void set_test_uint(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:IPacketTest)
 private:
  inline void set_has_test_uint();
  inline void clear_has_test_uint();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 test_uint_;
  friend void  protobuf_AddDesc_NetworkStructures_2eproto();
  friend void protobuf_AssignDesc_NetworkStructures_2eproto();
  friend void protobuf_ShutdownFile_NetworkStructures_2eproto();

  void InitAsDefaultInstance();
  static IPacketTest* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// IPacketTest

// required uint32 test_uint = 1;
inline bool IPacketTest::has_test_uint() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void IPacketTest::set_has_test_uint() {
  _has_bits_[0] |= 0x00000001u;
}
inline void IPacketTest::clear_has_test_uint() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void IPacketTest::clear_test_uint() {
  test_uint_ = 0u;
  clear_has_test_uint();
}
inline ::google::protobuf::uint32 IPacketTest::test_uint() const {
  // @@protoc_insertion_point(field_get:IPacketTest.test_uint)
  return test_uint_;
}
inline void IPacketTest::set_test_uint(::google::protobuf::uint32 value) {
  set_has_test_uint();
  test_uint_ = value;
  // @@protoc_insertion_point(field_set:IPacketTest.test_uint)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_NetworkStructures_2eproto__INCLUDED
